
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cmt_api;Mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: exclude.yml
logging:
  level:
    # 로거를 통해찍음.
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
server:
  port: 80