spring:
  config:
    activate:
      on-profile: local # 프로파일 설정값 설정
  datasource: # db 설정(h2)
    url: jdbc:h2:tcp://localhost/~/cmt_api;Mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa: # Jpa 설정
    hibernate:
      ddl-auto: none # DDL 실행
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3600