spring:
  profiles:
    default: local # 기본 프로파일 위치 설정
  config:
    import: # Import 할 외부 설정 파일 목록
      - exclude.yml
  session:
    redis:
      namespace: catchmetable:session # 세션을 저장하는 데 사용되는 키의 네임스페이스를 지정합니다.
server:
  servlet:
    session:
      cookie:
        path: / # 적용될 URL 경로
        name: JSESSIONID # 이름
        http-only: true # 쿠키에 대한 JS 접근을 제한.
        #secure : true # HTTPS 연결을 통해서만 전송가능. 아직 SSL을 적용하지않은 상태니까 주석 처리.
      timeout: 3600 # 세션 유효시간(단위:초)
  port: 80
